version: '3.7'

services:

  user-cmd-api:
    container_name: user-cmd-api
    image: user-cmd-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  user-query-api:
    container_name: user-query-api
    image: user-query-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8082
        published: 8082
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  bankacc-cmd-api:
    container_name: bankacc-cmd-api
    image: bankacc-cmd-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  bankacc-query-api:
    container_name: bankacc-query-api
    image: bankacc-query-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 2000
        published: 2000
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      
networks:
  default:
    external:
      name: springbankNet
